# Site settings
title: Heyal Solutions Ltd
email: sales@heyal.co.uk
description: Cloud Native and DevOps consultancy focusing on transforming businesses into customer focused delivey experts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://heyal.co.uk" # the base hostname & protocol for your site

twitter_username: alistair_hey
github_username: Waterdrips

# Build settings
markdown: kramdown
